//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИзготовлениеМебели
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductWorkShops = new HashSet<ProductWorkShops>();
        }
    
        public int Код { get; set; }
        public int КодТипПродукции { get; set; }
        public string НаименованиеПродукции { get; set; }
        public string Артикул { get; set; }
        public double МинСтоимостьДляПартнера { get; set; }
        public int КодОсновнойМатериал { get; set; }

        public int ВремяИзготовление
        {
            get
            {
                double resSumTime = ProductWorkShops.Where(item => item.КодПродукции == Код).Sum(item => item.ВремяИзготовления);
                return int.Parse(resSumTime.ToString("f0"));
            }
        }
    
        public virtual ProductMaterialType ProductMaterialType { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkShops> ProductWorkShops { get; set; }
    }
}
