//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИзготовлениеМебели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWorkShops
    {
        public int Код { get; set; }
        public int КодПродукции { get; set; }
        public int КодЦеха { get; set; }
        public double ВремяИзготовления { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual WorkShops WorkShops { get; set; }
    }
}
