//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИзготовлениеМебели
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkShops()
        {
            this.ProductWorkShops = new HashSet<ProductWorkShops>();
        }
    
        public int Код { get; set; }
        public string НазаваниеЦеха { get; set; }
        public int КодТипаЦеха { get; set; }
        public int КоличествоЧелДляПроизодства { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkShops> ProductWorkShops { get; set; }
        public virtual TypeWorkShops TypeWorkShops { get; set; }
    }
}
